"""
EDA for features generated by feature_engineeringv4.py.

Generates:
- dataset health checks (schema, duplicates, missingness)
- descriptive statistics for numeric features
- Pearson and Spearman correlation matrices (+ heatmap)
- correlation with target (is_insider) if present
- multicollinearity diagnostics (VIF)
- near-zero variance feature report
- text summary report

Usage:
  .\\venv\\Scripts\\python.exe scripts\\eda_featuresv4.py
"""

from __future__ import annotations

import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Iterable

import duckdb
import numpy as np
import pandas as pd
import yaml

try:
    import matplotlib.pyplot as plt

    HAS_PLOT = True
except Exception:
    HAS_PLOT = False

try:
    import seaborn as sns

    HAS_SNS = True
except Exception:
    HAS_SNS = False

try:
    from statsmodels.stats.outliers_influence import variance_inflation_factor

    HAS_VIF = True
except Exception:
    HAS_VIF = False


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def get_logger(logs_dir: Path) -> logging.Logger:
    logs_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    logger = logging.getLogger("EDAFeaturesV4")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    logger.propagate = False

    fmt = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    fh = logging.FileHandler(logs_dir / f"eda_featuresv4_{ts}.log", encoding="utf-8")
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(fmt)
    logger.addHandler(ch)

    return logger


def load_config(path: str | Path | None = None) -> dict:
    cfg_path = Path(path) if path else PROJECT_ROOT / "configs" / "config.yaml"
    with open(cfg_path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def list_feature_files(features_dir: Path) -> list[Path]:
    return sorted(
        p for p in features_dir.glob("slice_*/features.parquet") if p.is_file()
    )


def ensure_dirs(reports_dir: Path) -> tuple[Path, Path]:
    out_dir = reports_dir / "features_v4_eda"
    plots_dir = out_dir / "plots"
    out_dir.mkdir(parents=True, exist_ok=True)
    plots_dir.mkdir(parents=True, exist_ok=True)
    return out_dir, plots_dir


def quote_paths(paths: Iterable[Path]) -> str:
    return ", ".join(f"'{p.as_posix()}'" for p in paths)


def load_features_df(files: list[Path]) -> pd.DataFrame:
    con = duckdb.connect()
    rel = quote_paths(files)
    df = con.execute(f"SELECT * FROM read_parquet([{rel}])").df()
    con.close()
    if "window" in df.columns:
        df["window"] = pd.to_datetime(df["window"], errors="coerce", utc=True)
    return df


def schema_per_file(files: list[Path]) -> dict[str, list[tuple[str, str]]]:
    con = duckdb.connect()
    out: dict[str, list[tuple[str, str]]] = {}
    for fp in files:
        d = con.execute(
            f"DESCRIBE SELECT * FROM read_parquet('{fp.as_posix()}')"
        ).df()
        out[str(fp)] = list(zip(d["column_name"].tolist(), d["column_type"].tolist()))
    con.close()
    return out


def schema_consistency(schema_map: dict[str, list[tuple[str, str]]]) -> tuple[bool, str]:
    if not schema_map:
        return True, "No files."
    first_name = next(iter(schema_map))
    first_schema = schema_map[first_name]
    bad = [name for name, sch in schema_map.items() if sch != first_schema]
    if not bad:
        return True, "All feature files share the same schema."
    return False, f"Schema mismatch: {len(bad)} file(s)"


def duplicate_key_count(df: pd.DataFrame) -> int:
    if "user_id" not in df.columns or "window" not in df.columns:
        return 0
    return int(df.duplicated(subset=["user_id", "window"]).sum())


def missing_summary(df: pd.DataFrame) -> pd.DataFrame:
    miss = df.isna().mean().mul(100).sort_values(ascending=False)
    out = miss.reset_index()
    out.columns = ["feature", "missing_pct"]
    return out


def safe_numeric_df(df: pd.DataFrame) -> pd.DataFrame:
    num = df.select_dtypes(include=[np.number, "bool"]).copy()
    for c in num.columns:
        if str(num[c].dtype) == "bool":
            num[c] = num[c].astype(int)
    return num


def descriptive_stats(num_df: pd.DataFrame) -> pd.DataFrame:
    if num_df.empty:
        return pd.DataFrame()
    q = num_df.quantile([0.01, 0.05, 0.5, 0.95, 0.99]).T
    q.columns = ["p01", "p05", "p50", "p95", "p99"]
    out = pd.DataFrame(
        {
            "feature": num_df.columns,
            "count": num_df.count().values,
            "mean": num_df.mean().values,
            "std": num_df.std(ddof=1).values,
            "min": num_df.min().values,
            "max": num_df.max().values,
            "skew": num_df.skew(numeric_only=True).values,
            "kurtosis": num_df.kurt(numeric_only=True).values,
            "n_unique": num_df.nunique(dropna=True).values,
            "zero_pct": (num_df.eq(0).mean() * 100).values,
        }
    )
    out = out.merge(q.reset_index().rename(columns={"index": "feature"}), on="feature", how="left")
    return out.sort_values("feature").reset_index(drop=True)


def near_zero_variance(num_df: pd.DataFrame) -> pd.DataFrame:
    if num_df.empty:
        return pd.DataFrame()
    rows = []
    for c in num_df.columns:
        s = num_df[c].dropna()
        if s.empty:
            continue
        vc = s.value_counts(normalize=True, dropna=False)
        top_freq_ratio = float(vc.iloc[0]) if len(vc) else 0.0
        rows.append(
            {
                "feature": c,
                "variance": float(s.var(ddof=1)) if len(s) > 1 else 0.0,
                "n_unique": int(s.nunique()),
                "top_value_ratio": top_freq_ratio,
                "near_zero_variance_flag": int((s.nunique() <= 2 and top_freq_ratio > 0.95) or (s.var(ddof=1) < 1e-8)),
            }
        )
    out = pd.DataFrame(rows)
    if out.empty:
        return out
    return out.sort_values(["near_zero_variance_flag", "variance"], ascending=[False, True]).reset_index(drop=True)


def correlation_outputs(num_df: pd.DataFrame, out_dir: Path, plots_dir: Path) -> pd.DataFrame:
    if num_df.empty:
        return pd.DataFrame()
    pearson = num_df.corr(method="pearson", numeric_only=True)
    spearman = num_df.corr(method="spearman", numeric_only=True)
    pearson.to_csv(out_dir / "correlation_matrix_pearson.csv")
    spearman.to_csv(out_dir / "correlation_matrix_spearman.csv")

    if HAS_PLOT:
        fig = plt.figure(figsize=(14, 12))
        if HAS_SNS:
            sns.heatmap(pearson, cmap="coolwarm", center=0.0, linewidths=0.2, cbar=True)
        else:
            plt.imshow(pearson.values, cmap="coolwarm", aspect="auto")
            plt.colorbar()
            plt.xticks(range(len(pearson.columns)), pearson.columns, rotation=90, fontsize=6)
            plt.yticks(range(len(pearson.index)), pearson.index, fontsize=6)
        plt.title("Pearson Correlation Matrix (features v4)")
        plt.tight_layout()
        fig.savefig(plots_dir / "correlation_heatmap_pearson.png", dpi=180)
        plt.close(fig)

    upper = pearson.where(np.triu(np.ones(pearson.shape), k=1).astype(bool))
    pairs = (
        upper.stack()
        .reset_index()
        .rename(columns={"level_0": "feature_x", "level_1": "feature_y", 0: "corr"})
    )
    pairs["abs_corr"] = pairs["corr"].abs()
    pairs = pairs.sort_values("abs_corr", ascending=False).reset_index(drop=True)
    pairs.to_csv(out_dir / "top_feature_correlations.csv", index=False)
    return pairs


def target_correlation(num_df: pd.DataFrame, target_col: str = "is_insider") -> pd.DataFrame:
    if target_col not in num_df.columns:
        return pd.DataFrame()
    target = num_df[target_col]
    rows = []
    for c in num_df.columns:
        if c == target_col:
            continue
        s = num_df[c]
        if s.nunique(dropna=True) <= 1:
            corr = 0.0
        else:
            corr = float(pd.Series(s).corr(target))
            if np.isnan(corr):
                corr = 0.0
        rows.append({"feature": c, "corr_with_is_insider": corr, "abs_corr": abs(corr)})
    out = pd.DataFrame(rows)
    if out.empty:
        return out
    return out.sort_values("abs_corr", ascending=False).reset_index(drop=True)


def compute_vif(num_df: pd.DataFrame, max_features: int = 30) -> pd.DataFrame:
    if not HAS_VIF or num_df.empty:
        return pd.DataFrame()
    # Keep only variable columns and cap count for runtime stability.
    keep = [c for c in num_df.columns if num_df[c].nunique(dropna=True) > 1 and c != "is_insider"]
    if not keep:
        return pd.DataFrame()
    ranked = num_df[keep].var().sort_values(ascending=False).index.tolist()[:max_features]
    x = num_df[ranked].replace([np.inf, -np.inf], np.nan).fillna(0.0).astype(float)
    rows = []
    for i, c in enumerate(x.columns):
        try:
            v = float(variance_inflation_factor(x.values, i))
        except Exception:
            v = np.nan
        rows.append({"feature": c, "vif": v})
    out = pd.DataFrame(rows).sort_values("vif", ascending=False).reset_index(drop=True)
    return out


def write_summary(
    out_file: Path,
    files: list[Path],
    df: pd.DataFrame,
    schema_ok: bool,
    schema_note: str,
    dup_count: int,
    miss_df: pd.DataFrame,
    target_df: pd.DataFrame,
    nzv_df: pd.DataFrame,
    top_corr: pd.DataFrame,
    vif_df: pd.DataFrame,
) -> None:
    lines: list[str] = []
    lines.append("FEATURES_V4_EDA_SUMMARY")
    lines.append(f"files_count: {len(files)}")
    lines.append(f"rows_total: {len(df)}")
    lines.append(f"cols_total: {len(df.columns)}")
    if "user_id" in df.columns:
        lines.append(f"users: {df['user_id'].nunique()}")
    if "window" in df.columns and df["window"].notna().any():
        lines.append(f"window_min: {df['window'].min()} window_max: {df['window'].max()}")
    lines.append(f"schema_consistent: {schema_ok}")
    lines.append(f"schema_note: {schema_note}")
    lines.append(f"duplicate_user_window: {dup_count}")
    lines.append(f"plotting_enabled: {HAS_PLOT}")
    lines.append(f"vif_enabled: {HAS_VIF}")
    lines.append("")

    lines.append("MISSING_TOP_20")
    for _, r in miss_df.head(20).iterrows():
        lines.append(f"{r['feature']}: {r['missing_pct']:.4f}%")
    lines.append("")

    if not target_df.empty:
        lines.append("TOP_FEATURES_BY_ABS_CORR_WITH_IS_INSIDER_20")
        for _, r in target_df.head(20).iterrows():
            lines.append(f"{r['feature']}: corr={r['corr_with_is_insider']:.6f}")
        lines.append("")

    if not nzv_df.empty:
        flagged = nzv_df[nzv_df["near_zero_variance_flag"] == 1]
        lines.append(f"NEAR_ZERO_VARIANCE_FLAGGED: {len(flagged)}")
        for _, r in flagged.head(20).iterrows():
            lines.append(
                f"{r['feature']}: variance={r['variance']:.10f} top_value_ratio={r['top_value_ratio']:.4f}"
            )
        lines.append("")

    if not top_corr.empty:
        lines.append("TOP_ABS_CORRELATIONS_30")
        for _, r in top_corr.head(30).iterrows():
            lines.append(f"{r['feature_x']} <-> {r['feature_y']}: corr={r['corr']:.6f}")
        lines.append("")

    if not vif_df.empty:
        lines.append("TOP_VIF_20")
        for _, r in vif_df.head(20).iterrows():
            lines.append(f"{r['feature']}: vif={r['vif']:.4f}")
        lines.append("")

    lines.append("NOTES")
    lines.append("- Remove one feature in pairs with |corr| > 0.95.")
    lines.append("- Investigate features with VIF > 10 (high multicollinearity).")
    lines.append("- Remove or transform near-zero variance features.")
    lines.append("- Validate feature usefulness with is_insider correlation and downstream model CV.")

    out_file.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    t0 = time.perf_counter()
    cfg = load_config()
    features_dir = Path(cfg["output"]["features_dir"])
    reports_dir = Path(cfg["output"]["reports_dir"])
    out_dir, plots_dir = ensure_dirs(reports_dir)
    logger = get_logger(out_dir / "logs")
    logger.info("=" * 72)
    logger.info("EDA FEATURES V4 - START")
    logger.info("features_dir=%s", features_dir)
    logger.info("reports_dir=%s", reports_dir)
    logger.info("plotting_enabled=%s | seaborn_enabled=%s | vif_enabled=%s", HAS_PLOT, HAS_SNS, HAS_VIF)

    files = list_feature_files(features_dir)
    logger.info("feature_files_detected=%d", len(files))
    if not files:
        msg = f"No feature files found in {features_dir}/slice_*/features.parquet"
        (out_dir / "features_v4_summary.txt").write_text(msg, encoding="utf-8")
        logger.warning(msg)
        return

    t_step = time.perf_counter()
    schema_map = schema_per_file(files)
    schema_ok, schema_note = schema_consistency(schema_map)
    logger.info(
        "schema_check_done | consistent=%s | note=%s | elapsed=%.2fs",
        schema_ok, schema_note, time.perf_counter() - t_step
    )

    t_step = time.perf_counter()
    df = load_features_df(files)
    logger.info(
        "load_features_done | rows=%d | cols=%d | elapsed=%.2fs",
        len(df), len(df.columns), time.perf_counter() - t_step
    )

    t_step = time.perf_counter()
    dup_count = duplicate_key_count(df)
    miss_df = missing_summary(df)
    num_df = safe_numeric_df(df)
    logger.info(
        "health_checks_done | duplicate_user_window=%d | numeric_cols=%d | elapsed=%.2fs",
        dup_count, len(num_df.columns), time.perf_counter() - t_step
    )

    t_step = time.perf_counter()
    desc_df = descriptive_stats(num_df)
    nzv_df = near_zero_variance(num_df)
    top_corr = correlation_outputs(num_df, out_dir, plots_dir)
    target_df = target_correlation(num_df, target_col="is_insider")
    vif_df = compute_vif(num_df, max_features=30)
    logger.info(
        "stats_done | desc=%d | nzv=%d | corr_pairs=%d | target_corr=%d | vif=%d | elapsed=%.2fs",
        len(desc_df), len(nzv_df), len(top_corr), len(target_df), len(vif_df),
        time.perf_counter() - t_step
    )

    t_step = time.perf_counter()
    miss_df.to_csv(out_dir / "missing_summary.csv", index=False)
    if not desc_df.empty:
        desc_df.to_csv(out_dir / "descriptive_stats_numeric.csv", index=False)
    if not target_df.empty:
        target_df.to_csv(out_dir / "target_correlation_is_insider.csv", index=False)
    if not nzv_df.empty:
        nzv_df.to_csv(out_dir / "near_zero_variance_report.csv", index=False)
    if not vif_df.empty:
        vif_df.to_csv(out_dir / "vif_report.csv", index=False)
    logger.info("csv_exports_done | elapsed=%.2fs", time.perf_counter() - t_step)

    summary_file = out_dir / "features_v4_summary.txt"
    t_step = time.perf_counter()
    write_summary(
        summary_file,
        files,
        df,
        schema_ok,
        schema_note,
        dup_count,
        miss_df,
        target_df,
        nzv_df,
        top_corr,
        vif_df,
    )
    logger.info("summary_written | path=%s | elapsed=%.2fs", summary_file, time.perf_counter() - t_step)

    logger.info("outputs | tables_dir=%s | plots_dir=%s", out_dir, plots_dir)
    logger.info("EDA FEATURES V4 - DONE | total_elapsed=%.2fs", time.perf_counter() - t0)
    logger.info("=" * 72)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logging.getLogger("EDAFeaturesV4").exception("EDA FEATURES V4 - FAILED")
        raise
